[[main]]
  name = "About"
  weight = 1
  url = "/about/"
[[main]]
  name = "Skills"
  weight = 2
  url = "/skills/"
[[main]]
  name = "Experience"
  weight = 3
  url = "/experience/"
[[main]]
  name = "Notes"
  weight = 4
  url = "/notes/"
[[main]]
  name = "Contact"
  weight = 5
  url = "/contact/"