# baseurl = "https://alfonszelicko.com"
baseurl = "/"
title = "Alfons Zelicko"
languageCode = "en"
timeZone = "Europe/Prague"

canonifyurls = true # Enable to turn relative URLs into absolute.

[markup]
defaultMarkdownHandler = "goldmark"

[markup.goldmark.parser.attribute]
block = true

[markup.goldmark.extensions]
table = true
footnote = true

[markup.goldmark.renderer]
unsafe = true

[params]
    author = "Alfons Zelicko"
    info = "Software, Design, D&D"
    description = "My name is Alfons Zelicko, I am a software developer"
    keywords = "alfons zelicko, alfons, zelicko"
    keepItSimple = false
    favicon = "/images/favicon.png"

[[params.social]]
    name = "Email"
    weight = 1
    url = "/contact"
[[params.social]]
    name = "Github"
    weight = 2
    url = "https://github.com/alfonsZelicko"
[[params.social]]
    name = "LinkedIn"
    weight = 4
    url = "https://www.linkedin.com/in/alfons-zelicko-7a8645182/"

# Menu links
[[menu.main]]
    name = "About"
    weight = 1
    url  = "/about/"
[[menu.main]]
    name = "Skills"
    weight = 2
    url = "/skills/"
[[menu.main]]
    name = "Experience"
    weight = 3
    url = "/experience/"
[[menu.main]]
    name = "Contact"
    weight = 5
    url = "/contact/"
